import type { Metadata } from 'next';
import './globals.css';
import '../styles/main.scss';
import Header from '@/components/common/Header';
import Footer from '@/components/common/Footer';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <Theme className='text-white' appearance='dark'>
          <Header />
          {children}
          {/* <Footer /> */}
        </Theme>
      </body>
    </html>
  );
}
